### ISSUE TITLE
RemovedInDjango110Warning Error 

### ISSUE THREAD

**Issue by b3h3rkz** [dokterbob/django-newsletter#186]
I am running django1.9 and python3.4. Setup went well until i ran the `/manage.py runjob submit` command which gave me this error.

Does this have anything to do with running the command with newsletter? if not, what command do we use to avoid the error?

>  RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead

**Comment by claudep** [comment]
This is only a warning, so you can simply ignore it for now.
It was recently fixed in django-extensions (https://github.com/django-extensions/django-extensions/commit/160aaa80829a9e2cd45ff00d7054e9bb09393b98), so this warning will disappear automatically after an upcoming update of django-extensions.

**Comment by dokterbob** [comment]
Preferably, we'd remove dependency on django-extensions's cron and use the system cron instead with a custom management command as proposed in #96.

For now I'm closing this issue.
