### ISSUE TITLE
Submission marked as sent even though it failed

### ISSUE THREAD

**Issue by newearthmartin** [dokterbob/django-newsletter#210]
I was not connected to the internet so `runjob submit` failed with this error

`newsletter.models ERROR Message Martin Massera <martinmassera@...> to All Users failed with error: [Errno -3] Temporary failure in name resolution
`

However, the submission was marked as sent. The job should be either failing and tried again later, or the submission marked as fail.

**Comment by dokterbob** [comment]
This is intentional behaviour, implemented in https://github.com/dokterbob/django-newsletter/blob/master/newsletter/models.py#L644.

The reason for this is that the failure to submit a single message should not cause the entire submission to fail; there are newsletters submitted to tens of thousands of people and when one of them as an email address the mailserver rejects (i.e. because it's a nonexistant domain) the entire submission would fail.

Obviously, a more structural solution is to integrate per-submission per-subscription reporting.
