### ISSUE TITLE
add blocks in message templates so that they can be extended

### ISSUE THREAD

**Issue by newearthmartin** [dokterbob/django-newsletter#211]
Right now one needs to copy the whole template to be able to extend it , which is not very DRY. Maybe one only wants to update the footer for instance. There should be blocks in the templates so one could extend easily and only modify that.

**Comment by dokterbob** [comment]
At this point, the templates are intentionally kept minimal, precisely because we would expect every production user to override them. This goes especially for the (HTML) message templates, as one can expect every user to make their own layout.

In other words: the templates exist to provide:
1. An example.
2. Minimize the effort to a minimal working setup.

As an added benefit, not making assumptions as to the desired structure saves us from having to reach consensus on them. However, if you have any concrete suggestion on better ways of organizing templates (not just the footer), feel free to reopen the ticket with your concrete proposal.
