### ISSUE TITLE
Get 'real' client IP behind reverse proxy

### ISSUE THREAD

**Issue by mousasya3** [dokterbob/django-newsletter#226]
Hi,
I have used your module its really nice and useful
but when anyone subscribe to my newsletter and activate the subscription it doesn't  save his ip.
I'm using Django with Nginx and gunicorn.
can you help me with this issue please.
Thanks

**Comment by dokterbob** [comment]
Getting the client's remote address from the request is not as easy as it seems, as there is no universal standard way of doing this (although using `X-Forwarded-For` is the most common way). One way to tackle this is adding a `get_client_ip(request)` method which has a sensible default (`X-Forwarded-For` if available, `REMOTE_ADDR` otherwise). 

By creating a configuration option it becomes possible to override this to use other methods to retreive the address (like `django-ipware`). 

If you (or anyone) feels like implementing the above: great! I'm sure many users can and will appreciate (I will!)
