### ISSUE TITLE
Feedback/translations request: pre-release 0.9b1

### ISSUE THREAD

**Issue by dokterbob** [dokterbob/django-newsletter#302]
Dear contributer,

As there are breaking changes with the originally intended 0.8 release, I have chosen to make a 0.9 beta-release. Please report any issues you may find within 2 weeks, so that we can find any issues before a production release.

For more details, please see:
https://github.com/dokterbob/django-newsletter/releases/tag/v0.9b1

Also note that some of the strings have changed. If you are the maintainer of a translation, please take the time to update the strings.

Thanks!
Mathijs

@manikos @newearthmartin @studybuffalo @kutenai @aquilesC @gcallah

**Comment by dokterbob** [comment]
Addendum; the latest pre-release may be installed with: `pip install --pre django-newsletter`

**Comment by studybuffalo** [comment]
I am working on this right now, but wanted to have it documented for anyone else running into issues:

It is looking like there is no way to force `setuptools` to install a package from a specific URL if the package is found in PyPI. Pip 19.0+ no longer makes use of `dependency_links` and the new syntax to specify a URL will be overridden when pip finds the package on PyPI. It looks like the workarounds would require updating the install instructions to have users manually specify the URLs previously declared in `dependency_links` or installing `requirements.txt` directly, which I think is getting too messy. This made it past testing because the Travis file was installing the packages directly from the `requirements.txt` file rather than letting `setuptools` do it.

As for solutions, I think the top choices are:
1. Wait for `sorl-thumbnail` 12.6.0 to be released to PyPI
2. Update documentation to have Django 3.0 users to manually install the required sorl-thumbnail tarball
3. Remove the `sorl-thumbnail` dependency

I am looking into what option 3 would entail and see if it could be done without significant breaking changes.
