### ISSUE TITLE
Error sending e-mail with accented characters

### ISSUE THREAD

**Issue by lopesandre** [dokterbob/django-newsletter#83]
Hi,

When I try to subscribe with a non registered user using the form with "Name" and "Email", if I use an accented name, the E-mail is not sent. The error is:

UnicodeEncodeError('ascii', u'Dear Andr\xe9,\r\n\r\nyou, or someone in your name requested a subscription to Gui Chestnut Alert.\r\n\r\nIf you would like to confirm your subscription, please follow this activation link:\r\nhttp://example.com/en/new-season-start-alert/gui-chestnut-alert/subscription/some@email.com/subscribe/activate/1acb3e89050e876268c764fbca80c88db5423a28/\r\n\r\nKind regards,\r\nGui Chestnut Portugal', 9, 10, 'ordinal not in range(128)')

Here I'm trying to send the Name "André"

I've catch this error on views.py, class ActionRequestView, method form_valid

Using Master branch, Django 1.5.1

**Comment by newearthmartin** [comment]
It is a problem with django-newsletter. Facts:

-Unicode is permitted everywhere but in the addresses. From Django docs:

> Django’s email framework (in django.core.mail) supports Unicode transparently. You can use Unicode data in the message bodies and any headers. However, you’re still obligated to respect the requirements of the email specifications, so, for example, email addresses should use only ASCII characters.

-Say I have a chinese user of name 李志 and email some_email@gmail.com
-It will fail saying 
`Message` 李志 < some_email@gmail.com > to All Users failed with error: 'ascii' codec can't encode  ...

- So knowing that django is ok with unicode except in the address, there are two options if I have a unicode name for subscription: 

1. I take the name away for that user in my subscription. Then I can-t use the name in the email template :-1: 
2. django-newsletter takes the name away when sending the email, but allows me to keep using the name inside the template :+1:  

Clearly best answer is #2 so that makes it a problem of django-newsletter!

**Comment by sergei-maertens** [comment]
Fyi, Django < 1.10 had a problem with unicode in e-mail address encodings
on py3. It's fixed in 1.10

**Comment by newearthmartin** [comment]
hey, django 1.10 is still in alpha. Most users are not in django1.10. Most probably lot-s of emails are not being sent because of this (and maybe admins dont even realize!)
I have a very small fix for this, I will send you a pull request if you are interested.

**Comment by sergei-maertens** [comment]
It was just some extra context around the issue :) it should be handled for
1.9 anyway per the compatibility policy

**Comment by newearthmartin** [comment]
Ah! I cant upgrade to django 1.9 yet because of my dependencies, so I still need my fix :)
I added a check for the django version in the fix and sent a pull request. Its just a little function, which Im unsure where to put.

**Comment by claudep** [comment]
Could you please attach the error traceback so we can see where it fails?
